# Generated by Django 5.2.1 on 2025-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=50)),
                ('stuemail', models.EmailField(max_length=254)),
                ('studetails', models.CharField(max_length=300)),
                ('stuphone', models.BigIntegerField()),
                ('studob', models.DateField()),
                ('stuedu', models.CharField(max_length=50)),
                ('stugender', models.CharField(max_length=50)),
                ('stuimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sturesume', models.FileField(blank=True, null=True, upload_to='files/')),
                ('stupass', models.CharField(max_length=50)),
            ],
        ),
    ]
