# Generated by Django 5.2.1 on 2025-05-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='studetails',
            new_name='studetail',
        ),
    ]
