# Generated by Django 5.2.1 on 2025-05-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=100)),
                ('stuemail', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='query',
            old_name='email',
            new_name='stuemail',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='name',
            new_name='stuname',
        ),
    ]
