# Generated by Django 5.2.1 on 2025-05-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_stuquery_rename_email_query_stuemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuquery',
            name='response',
        ),
    ]
