# Generated by Django 5.2.1 on 2025-05-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_stuquery_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.AddField(
            model_name='stuquery',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
