# Generated by Django 5.2.1 on 2025-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_query_stuquery_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='stuedu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='stugender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
