# Generated by Django 5.2.1 on 2025-05-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_students_studob_alter_students_stuedu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StuQuery',
            new_name='UserQuery',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Users',
        ),
    ]
