# Generated by Django 5.2.3 on 2025-06-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('payment', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=200)),
                ('productPrice', models.IntegerField()),
                ('productImage', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
