# Generated by Django 5.2.3 on 2025-06-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='productImage',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='productPrice',
        ),
    ]
