# Generated by Django 5.2 on 2025-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_s_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_no',
            field=models.IntegerField(default=1),
        ),
    ]
