# Generated by Django 5.2 on 2025-05-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_s_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_no',
        ),
    ]
