# Generated by Django 5.2 on 2025-05-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
