# Generated by Django 5.2.1 on 2025-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
