# Generated by Django 5.2 on 2025-04-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='aadhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.aadhar', to_field='aadhar_no'),
        ),
    ]
