# Generated by Django 5.2 on 2025-05-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department'),
        ),
    ]
