# Generated by Django 5.2 on 2025-05-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('book', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
