# Generated by Django 5.2 on 2025-05-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='stuemial',
            new_name='stuemail',
        ),
        migrations.AlterField(
            model_name='students',
            name='stuimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='stuphone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='sturesume',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
