# Generated by Django 5.2 on 2025-04-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'verbose_name': 'MyCustomModel'},
        ),
        migrations.AlterModelTable(
            name='baseinfo',
            table='Student',
        ),
    ]
